### PR TITLE
porting strict context parser to context parser

### PR DESCRIPTION
**Pull request by neraliu**
This PR includes the following changes, please comment

* The function of Strict Context Parser will be added to the Parser and its corresponding features can be enabled through config object as shown below (default value)
```
var config = {
  enableInputPreProcessing: true,
  enableCanonicalization: false,
  enableIEConditionalComments: false,
  enableStateTracking: true
};
var p = new Parser(config)
```

* remove of the parsePartial function and use contextualize function for the context analysis.
* add the logic to avoid the input string split and array join if the canonicalization is disable to improve the performance.

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by adon-at-work** [comment]
Some hesitations on the consolidation. 
- input pre processing and null replacement need the array split and join too 
- contextualize used to give funny states if it's fed with chunked inputs. Modifying it will have backward compatibility considerations
- contextualize() from history does not return anything, conditionally returning modified inputs depending on config seems not very ideal as a public API. this also prohibits other perwalk handlers from doing input modifications. 

My two cents...

**Comment by neraliu** [comment]
i have the performance consideration of the the array split / join, so in this PR, i will set all the new feature default as false first before we enhance it in next round.

**Comment by neraliu** [comment]
for the contextualize api, we should make it align in this round of consolidation and bump up the major versions. in summary, there are 2 use cases right now, one is the html purifier for parsing completed html input, while secure-handlebars require to parse chunked input as it needs to walk through different conditional logic on the template.

**Comment by neraliu** [comment]
updating the default behavior of the context parser - all new feature will be disable by default

```
var config = {
  enableInputPreProcessing: false,
  enableCanonicalization: false,
  enableIEConditionalComments: false,
  enableStateTracking: true
};
var p = new Parser(config)
```

**Pull request merged**
