### PR TITLE
Upgrade to provide event-based interfaces

### PR DESCRIPTION
**Pull request by adon-at-work**
Upgraded to open event-based interfaces, while maintaining backward compatibility for contextualize, beforeWalk and afterWalk.

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by adon-at-work** [comment]
@yukinying / @neraliu , please help review and merge. thanks.

**Comment by yukinying** [comment]
can you provide a benchmark result before and after the patch so we know it would not affect the processing speed? thanks!

**Comment by adon-at-work** [comment]
Code updated.
- added event-based interfaces
- apply toLowerCase() to tagName and attrName only when needed (to offset the performance of adding new feature). 

Stats: (Avg. over 5 times using bin/benchmark)
- Before this PR: 24.88MB/sec 
- After this PR: 26.00MB/sec

**Comment by adon-at-work** [comment]
These few lines of code changes might break dependent packages/projects who directly access the internal variables:
https://github.com/yahoo/context-parser/pull/16/files#diff-453c94db9d68bf214cb0505c0e0791b5L21

**Comment by yukinying** [comment]
Is there a particular reason you would like those internal variable get renamed?

**Comment by adon-at-work** [comment]
it's unlike the original implementation which calls toLowerCase() for every single char, but now toLowerCase() is called only when people access it using public getters like getAttributeName() and getStartTagName(). this has improved the benchmark quite significantly (a few MB/sec).

renaming those internal variables is to get dependent projects break if they've replied on them, versus keeping the variable names intact and break others' assumption that they're always in lower case.

**Pull request merged**
