### PR TITLE
make afterwalk function prototype consistent with beforewalk

### PR DESCRIPTION
**Pull request by neraliu**
a minor code clean up for afterwalk and beforewalk

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by adon-at-work** [comment]
pls update the dist/ and the following too: 
https://github.com/yahoo/context-parser/blob/c98cee96ef538680a604dec3a1e38ce9c4e0649d/tests/unit/run-bug-spec.js#L24-L29

**Comment by neraliu** [comment]
recheck all the code / test cases with afterWalk function signature

**Comment by yukinying** [comment]
can we combine this to pull request #16 ?

**Comment by adon-at-work** [comment]
this is no longer needed if https://github.com/yahoo/context-parser/pull/16 is merged.

**Comment by neraliu** [comment]
agreed

**Pull request closed without merging**
