### PR TITLE
Optimize n fix bug

### PR DESCRIPTION
**Pull request by yukinying**
Please don't merge until we patch context-parse-handlebar altogether.

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by yukinying** [comment]
Here is the result of the benchmark, on a 1MB file I randomly crafted:

```
$ bin/benchmark
context-parser runs at a speed of 12.903225806451612 MB per seconds [0.0775 second per MB].
parse5 runs at a speed of 4.618937644341801 MB per seconds [0.2165 second per MB].
gumbo-parser runs at a speed of 2.1079258010118043 MB per seconds [0.4744 second per MB].
high5 runs at a speed of 21.83406113537118 MB per seconds [0.0458 second per MB].
htmlparser2 runs at a speed of 24.63054187192118 MB per seconds [0.040600000000000004 second per MB].
```

Note that high5 and htmlparser2 are not yet html5 compliant, and their code is heavily optimized that if you add any extra stream handler in them, their performance will be heavily impacted. So I think our optimization is good enough at this point.

**Comment by neraliu** [comment]
i found you decouple some logic to the parent class of FastParser, and I suppose all the APIs remain the same?

**Comment by yukinying** [comment]
Yes.

**Pull request merged**
